insert into "group" (id, subject_area_id, name) values (1, 95, 'Champions');
insert into "group" (id, subject_area_id, name) values (2, 88, 'Champions');
insert into "group" (id, subject_area_id, name) values (3, 78, 'Closers');
insert into "group" (id, subject_area_id, name) values (4, 96, 'Tremendous');
insert into "group" (id, subject_area_id, name) values (5, 10, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (6, 70, 'Finishers');
insert into "group" (id, subject_area_id, name) values (7, 41, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (8, 13, 'Champions');
insert into "group" (id, subject_area_id, name) values (9, 46, 'Strivers');
insert into "group" (id, subject_area_id, name) values (10, 14, 'Closers');
insert into "group" (id, subject_area_id, name) values (11, 58, 'Strivers');
insert into "group" (id, subject_area_id, name) values (12, 1, 'Strivers');
insert into "group" (id, subject_area_id, name) values (13, 54, 'Groundbreakers');
insert into "group" (id, subject_area_id, name) values (14, 66, 'Closers');
insert into "group" (id, subject_area_id, name) values (15, 17, 'Enforcers');
insert into "group" (id, subject_area_id, name) values (16, 57, 'Champions');
insert into "group" (id, subject_area_id, name) values (17, 12, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (18, 56, 'Finishers');
insert into "group" (id, subject_area_id, name) values (19, 78, 'Strivers');
insert into "group" (id, subject_area_id, name) values (20, 62, 'Tremendous');
insert into "group" (id, subject_area_id, name) values (21, 63, 'Innovators');
insert into "group" (id, subject_area_id, name) values (22, 37, 'Champions');
insert into "group" (id, subject_area_id, name) values (23, 62, 'Ultimate');
insert into "group" (id, subject_area_id, name) values (24, 70, 'Champions');
insert into "group" (id, subject_area_id, name) values (25, 42, 'Finishers');
insert into "group" (id, subject_area_id, name) values (26, 36, 'Tremendous');
insert into "group" (id, subject_area_id, name) values (27, 100, 'Champions');
insert into "group" (id, subject_area_id, name) values (28, 68, 'Champions');
insert into "group" (id, subject_area_id, name) values (29, 41, 'Innovators');
insert into "group" (id, subject_area_id, name) values (30, 28, 'Ultimate');
insert into "group" (id, subject_area_id, name) values (31, 23, 'Innovators');
insert into "group" (id, subject_area_id, name) values (32, 3, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (33, 2, 'Tremendous');
insert into "group" (id, subject_area_id, name) values (34, 45, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (35, 36, 'Wednesday Warriors');
insert into "group" (id, subject_area_id, name) values (36, 18, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (37, 87, 'Closers');
insert into "group" (id, subject_area_id, name) values (38, 95, 'Champions');
insert into "group" (id, subject_area_id, name) values (39, 74, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (40, 33, 'Finishers');
insert into "group" (id, subject_area_id, name) values (41, 37, 'Enforcers');
insert into "group" (id, subject_area_id, name) values (42, 55, 'Strivers');
insert into "group" (id, subject_area_id, name) values (43, 100, 'Innovators');
insert into "group" (id, subject_area_id, name) values (44, 28, 'Champions');
insert into "group" (id, subject_area_id, name) values (45, 14, 'Wednesday Warriors');
insert into "group" (id, subject_area_id, name) values (46, 92, 'Closers');
insert into "group" (id, subject_area_id, name) values (47, 32, 'Enforcers');
insert into "group" (id, subject_area_id, name) values (48, 69, 'Wednesday Warriors');
insert into "group" (id, subject_area_id, name) values (49, 72, 'Groundbreakers');
insert into "group" (id, subject_area_id, name) values (50, 14, 'Wednesday Warriors');
insert into "group" (id, subject_area_id, name) values (51, 28, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (52, 47, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (53, 95, 'Wednesday Warriors');
insert into "group" (id, subject_area_id, name) values (54, 44, 'Finishers');
insert into "group" (id, subject_area_id, name) values (55, 14, 'Wednesday Warriors');
insert into "group" (id, subject_area_id, name) values (56, 45, 'Enforcers');
insert into "group" (id, subject_area_id, name) values (57, 45, 'Finishers');
insert into "group" (id, subject_area_id, name) values (58, 43, 'Ultimate');
insert into "group" (id, subject_area_id, name) values (59, 1, 'Ultimate');
insert into "group" (id, subject_area_id, name) values (60, 9, 'Strivers');
insert into "group" (id, subject_area_id, name) values (61, 53, 'Champions');
insert into "group" (id, subject_area_id, name) values (62, 61, 'Innovators');
insert into "group" (id, subject_area_id, name) values (63, 97, 'Ultimate');
insert into "group" (id, subject_area_id, name) values (64, 27, 'Champions');
insert into "group" (id, subject_area_id, name) values (65, 53, 'Champions');
insert into "group" (id, subject_area_id, name) values (66, 57, 'Wednesday Warriors');
insert into "group" (id, subject_area_id, name) values (67, 17, 'Champions');
insert into "group" (id, subject_area_id, name) values (68, 7, 'Champions');
insert into "group" (id, subject_area_id, name) values (69, 95, 'Enforcers');
insert into "group" (id, subject_area_id, name) values (70, 46, 'Enforcers');
insert into "group" (id, subject_area_id, name) values (71, 94, 'Tremendous');
insert into "group" (id, subject_area_id, name) values (72, 43, 'Finishers');
insert into "group" (id, subject_area_id, name) values (73, 50, 'Groundbreakers');
insert into "group" (id, subject_area_id, name) values (74, 14, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (75, 38, 'Strivers');
insert into "group" (id, subject_area_id, name) values (76, 7, 'Groundbreakers');
insert into "group" (id, subject_area_id, name) values (77, 66, 'Innovators');
insert into "group" (id, subject_area_id, name) values (78, 93, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (79, 27, 'Champions');
insert into "group" (id, subject_area_id, name) values (80, 2, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (81, 46, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (82, 97, 'Enforcers');
insert into "group" (id, subject_area_id, name) values (83, 64, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (84, 27, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (85, 76, 'Innovators');
insert into "group" (id, subject_area_id, name) values (86, 100, 'Closers');
insert into "group" (id, subject_area_id, name) values (87, 3, 'Enforcers');
insert into "group" (id, subject_area_id, name) values (88, 41, 'Strivers');
insert into "group" (id, subject_area_id, name) values (89, 76, 'Finishers');
insert into "group" (id, subject_area_id, name) values (90, 79, 'Champions');
insert into "group" (id, subject_area_id, name) values (91, 23, 'Enforcers');
insert into "group" (id, subject_area_id, name) values (92, 49, 'Groundbreakers');
insert into "group" (id, subject_area_id, name) values (93, 59, 'Champions');
insert into "group" (id, subject_area_id, name) values (94, 1, 'Champions');
insert into "group" (id, subject_area_id, name) values (95, 85, 'Champions');
insert into "group" (id, subject_area_id, name) values (96, 50, 'Finishers');
insert into "group" (id, subject_area_id, name) values (97, 13, 'Closers');
insert into "group" (id, subject_area_id, name) values (98, 3, 'Innovators');
insert into "group" (id, subject_area_id, name) values (99, 89, 'Mission Implausible');
insert into "group" (id, subject_area_id, name) values (100, 63, 'Closers');
