insert into subject_area (id, budget_id, title) values (1, 217, 'Information Systems');
insert into subject_area (id, budget_id, title) values (2, 45, 'Economics');
insert into subject_area (id, budget_id, title) values (3, 15, 'Computer Science');
insert into subject_area (id, budget_id, title) values (4, 174, 'Game Development');
insert into subject_area (id, budget_id, title) values (5, 27, 'Information Systems');
insert into subject_area (id, budget_id, title) values (6, 122, 'Law');
insert into subject_area (id, budget_id, title) values (7, 66, 'Law');
insert into subject_area (id, budget_id, title) values (8, 140, 'Game Development');
insert into subject_area (id, budget_id, title) values (9, 124, 'Information Systems');
insert into subject_area (id, budget_id, title) values (10, 91, 'Sport');
insert into subject_area (id, budget_id, title) values (11, 1, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (12, 185, 'Game Development');
insert into subject_area (id, budget_id, title) values (13, 188, 'Computer Science');
insert into subject_area (id, budget_id, title) values (14, 193, 'Economics');
insert into subject_area (id, budget_id, title) values (15, 134, 'Architecture');
insert into subject_area (id, budget_id, title) values (16, 21, 'Law');
insert into subject_area (id, budget_id, title) values (17, 233, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (18, 63, 'Information Systems');
insert into subject_area (id, budget_id, title) values (19, 164, 'Architecture');
insert into subject_area (id, budget_id, title) values (20, 214, 'Game Development');
insert into subject_area (id, budget_id, title) values (21, 1, 'Architecture');
insert into subject_area (id, budget_id, title) values (22, 7, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (23, 127, 'Information Systems');
insert into subject_area (id, budget_id, title) values (24, 146, 'Economics');
insert into subject_area (id, budget_id, title) values (25, 221, 'Information Systems');
insert into subject_area (id, budget_id, title) values (26, 12, 'Architecture');
insert into subject_area (id, budget_id, title) values (27, 50, 'Economics');
insert into subject_area (id, budget_id, title) values (28, 139, 'Computer Science');
insert into subject_area (id, budget_id, title) values (29, 40, 'Game Development');
insert into subject_area (id, budget_id, title) values (30, 165, 'Computer Science');
insert into subject_area (id, budget_id, title) values (31, 52, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (32, 144, 'Game Development');
insert into subject_area (id, budget_id, title) values (33, 204, 'Sport');
insert into subject_area (id, budget_id, title) values (34, 58, 'Medicine');
insert into subject_area (id, budget_id, title) values (35, 60, 'Mechanical');
insert into subject_area (id, budget_id, title) values (36, 167, 'Engineering');
insert into subject_area (id, budget_id, title) values (37, 151, 'Computer Science');
insert into subject_area (id, budget_id, title) values (38, 54, 'Medicine');
insert into subject_area (id, budget_id, title) values (39, 123, 'Business');
insert into subject_area (id, budget_id, title) values (40, 199, 'Computer Science');
insert into subject_area (id, budget_id, title) values (41, 58, 'Computer Science');
insert into subject_area (id, budget_id, title) values (42, 248, 'Medicine');
insert into subject_area (id, budget_id, title) values (43, 103, 'Architecture');
insert into subject_area (id, budget_id, title) values (44, 153, 'Economics');
insert into subject_area (id, budget_id, title) values (45, 193, 'Information Systems');
insert into subject_area (id, budget_id, title) values (46, 84, 'Computer Science');
insert into subject_area (id, budget_id, title) values (47, 214, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (48, 14, 'Computer Science');
insert into subject_area (id, budget_id, title) values (49, 185, 'Game Development');
insert into subject_area (id, budget_id, title) values (50, 44, 'Economics');
insert into subject_area (id, budget_id, title) values (51, 4, 'Sport');
insert into subject_area (id, budget_id, title) values (52, 215, 'Information Systems');
insert into subject_area (id, budget_id, title) values (53, 211, 'Computer Science');
insert into subject_area (id, budget_id, title) values (54, 15, 'Computer Science');
insert into subject_area (id, budget_id, title) values (55, 201, 'Mechanical');
insert into subject_area (id, budget_id, title) values (56, 135, 'Medicine');
insert into subject_area (id, budget_id, title) values (57, 238, 'Medicine');
insert into subject_area (id, budget_id, title) values (58, 80, 'Sport');
insert into subject_area (id, budget_id, title) values (59, 96, 'Engineering');
insert into subject_area (id, budget_id, title) values (60, 95, 'Game Development');
insert into subject_area (id, budget_id, title) values (61, 181, 'Law');
insert into subject_area (id, budget_id, title) values (62, 97, 'Law');
insert into subject_area (id, budget_id, title) values (63, 54, 'Engineering');
insert into subject_area (id, budget_id, title) values (64, 150, 'Game Development');
insert into subject_area (id, budget_id, title) values (65, 29, 'Sport');
insert into subject_area (id, budget_id, title) values (66, 96, 'Medicine');
insert into subject_area (id, budget_id, title) values (67, 61, 'Law');
insert into subject_area (id, budget_id, title) values (68, 234, 'Information Systems');
insert into subject_area (id, budget_id, title) values (69, 2, 'Medicine');
insert into subject_area (id, budget_id, title) values (70, 127, 'Game Development');
insert into subject_area (id, budget_id, title) values (71, 95, 'Information Systems');
insert into subject_area (id, budget_id, title) values (72, 128, 'Architecture');
insert into subject_area (id, budget_id, title) values (73, 21, 'Engineering');
insert into subject_area (id, budget_id, title) values (74, 155, 'Medicine');
insert into subject_area (id, budget_id, title) values (75, 114, 'Engineering');
insert into subject_area (id, budget_id, title) values (76, 194, 'Architecture');
insert into subject_area (id, budget_id, title) values (77, 167, 'Law');
insert into subject_area (id, budget_id, title) values (78, 1, 'Business');
insert into subject_area (id, budget_id, title) values (79, 87, 'Law');
insert into subject_area (id, budget_id, title) values (80, 12, 'Business');
insert into subject_area (id, budget_id, title) values (81, 216, 'Computer Science');
insert into subject_area (id, budget_id, title) values (82, 231, 'Economics');
insert into subject_area (id, budget_id, title) values (83, 118, 'Engineering');
insert into subject_area (id, budget_id, title) values (84, 203, 'Business');
insert into subject_area (id, budget_id, title) values (85, 177, 'Mechanical');
insert into subject_area (id, budget_id, title) values (86, 103, 'Economics');
insert into subject_area (id, budget_id, title) values (87, 114, 'Computer Science');
insert into subject_area (id, budget_id, title) values (88, 4, 'Medicine');
insert into subject_area (id, budget_id, title) values (89, 41, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (90, 184, 'Computer Science');
insert into subject_area (id, budget_id, title) values (91, 222, 'Economics');
insert into subject_area (id, budget_id, title) values (92, 17, 'Law');
insert into subject_area (id, budget_id, title) values (93, 32, 'Law');
insert into subject_area (id, budget_id, title) values (94, 97, 'Sport');
insert into subject_area (id, budget_id, title) values (95, 219, 'Business');
insert into subject_area (id, budget_id, title) values (96, 42, 'Information Systems');
insert into subject_area (id, budget_id, title) values (97, 11, 'Medicine');
insert into subject_area (id, budget_id, title) values (98, 33, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (99, 8, 'Game Development');
insert into subject_area (id, budget_id, title) values (100, 240, 'Sport');
insert into subject_area (id, budget_id, title) values (101, 231, 'Information Systems');
insert into subject_area (id, budget_id, title) values (102, 194, 'Medicine');
insert into subject_area (id, budget_id, title) values (103, 66, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (104, 112, 'Computer Science');
insert into subject_area (id, budget_id, title) values (105, 49, 'Sport');
insert into subject_area (id, budget_id, title) values (106, 84, 'Mechanical');
insert into subject_area (id, budget_id, title) values (107, 8, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (108, 7, 'Engineering');
insert into subject_area (id, budget_id, title) values (109, 109, 'Computer Science');
insert into subject_area (id, budget_id, title) values (110, 207, 'Information Systems');
insert into subject_area (id, budget_id, title) values (111, 30, 'Mechanical');
insert into subject_area (id, budget_id, title) values (112, 74, 'Sport');
insert into subject_area (id, budget_id, title) values (113, 94, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (114, 90, 'Sport');
insert into subject_area (id, budget_id, title) values (115, 96, 'Information Systems');
insert into subject_area (id, budget_id, title) values (116, 9, 'Architecture');
insert into subject_area (id, budget_id, title) values (117, 152, 'Sport');
insert into subject_area (id, budget_id, title) values (118, 235, 'Economics');
insert into subject_area (id, budget_id, title) values (119, 94, 'Economics');
insert into subject_area (id, budget_id, title) values (120, 84, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (121, 197, 'Information Systems');
insert into subject_area (id, budget_id, title) values (122, 227, 'Engineering');
insert into subject_area (id, budget_id, title) values (123, 56, 'Business');
insert into subject_area (id, budget_id, title) values (124, 127, 'Mechanical');
insert into subject_area (id, budget_id, title) values (125, 68, 'Game Development');
insert into subject_area (id, budget_id, title) values (126, 125, 'Business');
insert into subject_area (id, budget_id, title) values (127, 23, 'Game Development');
insert into subject_area (id, budget_id, title) values (128, 129, 'Law');
insert into subject_area (id, budget_id, title) values (129, 186, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (130, 19, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (131, 158, 'Computer Science');
insert into subject_area (id, budget_id, title) values (132, 248, 'Law');
insert into subject_area (id, budget_id, title) values (133, 167, 'Computer Science');
insert into subject_area (id, budget_id, title) values (134, 129, 'Business');
insert into subject_area (id, budget_id, title) values (135, 206, 'Sport');
insert into subject_area (id, budget_id, title) values (136, 223, 'Mechanical');
insert into subject_area (id, budget_id, title) values (137, 248, 'Computer Science');
insert into subject_area (id, budget_id, title) values (138, 26, 'Architecture');
insert into subject_area (id, budget_id, title) values (139, 32, 'Information Systems');
insert into subject_area (id, budget_id, title) values (140, 29, 'Information Systems');
insert into subject_area (id, budget_id, title) values (141, 78, 'Medicine');
insert into subject_area (id, budget_id, title) values (142, 194, 'Game Development');
insert into subject_area (id, budget_id, title) values (143, 186, 'Sport');
insert into subject_area (id, budget_id, title) values (144, 34, 'Information Systems');
insert into subject_area (id, budget_id, title) values (145, 190, 'Economics');
insert into subject_area (id, budget_id, title) values (146, 193, 'Computer Science');
insert into subject_area (id, budget_id, title) values (147, 175, 'Law');
insert into subject_area (id, budget_id, title) values (148, 131, 'Mechanical');
insert into subject_area (id, budget_id, title) values (149, 116, 'Business');
insert into subject_area (id, budget_id, title) values (150, 176, 'Medicine');
insert into subject_area (id, budget_id, title) values (151, 111, 'Architecture');
insert into subject_area (id, budget_id, title) values (152, 152, 'Engineering');
insert into subject_area (id, budget_id, title) values (153, 84, 'Computer Science');
insert into subject_area (id, budget_id, title) values (154, 247, 'Business');
insert into subject_area (id, budget_id, title) values (155, 27, 'Law');
insert into subject_area (id, budget_id, title) values (156, 91, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (157, 104, 'Law');
insert into subject_area (id, budget_id, title) values (158, 30, 'Business');
insert into subject_area (id, budget_id, title) values (159, 98, 'Sport');
insert into subject_area (id, budget_id, title) values (160, 103, 'Engineering');
insert into subject_area (id, budget_id, title) values (161, 221, 'Information Systems');
insert into subject_area (id, budget_id, title) values (162, 214, 'Law');
insert into subject_area (id, budget_id, title) values (163, 187, 'Game Development');
insert into subject_area (id, budget_id, title) values (164, 234, 'Law');
insert into subject_area (id, budget_id, title) values (165, 75, 'Engineering');
insert into subject_area (id, budget_id, title) values (166, 126, 'Business');
insert into subject_area (id, budget_id, title) values (167, 189, 'Information Systems');
insert into subject_area (id, budget_id, title) values (168, 224, 'Computer Science');
insert into subject_area (id, budget_id, title) values (169, 172, 'Law');
insert into subject_area (id, budget_id, title) values (170, 171, 'Business');
insert into subject_area (id, budget_id, title) values (171, 200, 'Business');
insert into subject_area (id, budget_id, title) values (172, 54, 'Sport');
insert into subject_area (id, budget_id, title) values (173, 23, 'Medicine');
insert into subject_area (id, budget_id, title) values (174, 175, 'Engineering');
insert into subject_area (id, budget_id, title) values (175, 239, 'Medicine');
insert into subject_area (id, budget_id, title) values (176, 72, 'Medicine');
insert into subject_area (id, budget_id, title) values (177, 160, 'Architecture');
insert into subject_area (id, budget_id, title) values (178, 108, 'Engineering');
insert into subject_area (id, budget_id, title) values (179, 148, 'Business');
insert into subject_area (id, budget_id, title) values (180, 132, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (181, 29, 'Medicine');
insert into subject_area (id, budget_id, title) values (182, 52, 'Business');
insert into subject_area (id, budget_id, title) values (183, 170, 'Sport');
insert into subject_area (id, budget_id, title) values (184, 248, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (185, 33, 'Game Development');
insert into subject_area (id, budget_id, title) values (186, 71, 'Game Development');
insert into subject_area (id, budget_id, title) values (187, 18, 'Information Systems');
insert into subject_area (id, budget_id, title) values (188, 60, 'Business');
insert into subject_area (id, budget_id, title) values (189, 86, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (190, 238, 'Computer Science');
insert into subject_area (id, budget_id, title) values (191, 131, 'Law');
insert into subject_area (id, budget_id, title) values (192, 67, 'Medicine');
insert into subject_area (id, budget_id, title) values (193, 66, 'Business');
insert into subject_area (id, budget_id, title) values (194, 112, 'Engineering');
insert into subject_area (id, budget_id, title) values (195, 54, 'Medicine');
insert into subject_area (id, budget_id, title) values (196, 53, 'Economics');
insert into subject_area (id, budget_id, title) values (197, 59, 'Law');
insert into subject_area (id, budget_id, title) values (198, 5, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (199, 18, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (200, 22, 'Mechanical');
insert into subject_area (id, budget_id, title) values (201, 40, 'Economics');
insert into subject_area (id, budget_id, title) values (202, 37, 'Information Systems');
insert into subject_area (id, budget_id, title) values (203, 110, 'Medicine');
insert into subject_area (id, budget_id, title) values (204, 137, 'Economics');
insert into subject_area (id, budget_id, title) values (205, 216, 'Law');
insert into subject_area (id, budget_id, title) values (206, 107, 'Economics');
insert into subject_area (id, budget_id, title) values (207, 60, 'Game Development');
insert into subject_area (id, budget_id, title) values (208, 126, 'Engineering');
insert into subject_area (id, budget_id, title) values (209, 39, 'Computer Science');
insert into subject_area (id, budget_id, title) values (210, 170, 'Economics');
insert into subject_area (id, budget_id, title) values (211, 35, 'Computer Science');
insert into subject_area (id, budget_id, title) values (212, 101, 'Game Development');
insert into subject_area (id, budget_id, title) values (213, 49, 'Architecture');
insert into subject_area (id, budget_id, title) values (214, 178, 'Mechanical');
insert into subject_area (id, budget_id, title) values (215, 175, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (216, 198, 'Business');
insert into subject_area (id, budget_id, title) values (217, 194, 'Game Development');
insert into subject_area (id, budget_id, title) values (218, 99, 'Engineering');
insert into subject_area (id, budget_id, title) values (219, 161, 'Game Development');
insert into subject_area (id, budget_id, title) values (220, 205, 'Sport');
insert into subject_area (id, budget_id, title) values (221, 86, 'Computer Science');
insert into subject_area (id, budget_id, title) values (222, 91, 'Information Systems');
insert into subject_area (id, budget_id, title) values (223, 250, 'Mechanical');
insert into subject_area (id, budget_id, title) values (224, 148, 'Economics');
insert into subject_area (id, budget_id, title) values (225, 189, 'Computer Science');
insert into subject_area (id, budget_id, title) values (226, 47, 'Law');
insert into subject_area (id, budget_id, title) values (227, 112, 'Architecture');
insert into subject_area (id, budget_id, title) values (228, 98, 'Information Systems');
insert into subject_area (id, budget_id, title) values (229, 156, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (230, 9, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (231, 195, 'Information Systems');
insert into subject_area (id, budget_id, title) values (232, 248, 'Architecture');
insert into subject_area (id, budget_id, title) values (233, 244, 'Business');
insert into subject_area (id, budget_id, title) values (234, 81, 'Engineering');
insert into subject_area (id, budget_id, title) values (235, 112, 'Sport');
insert into subject_area (id, budget_id, title) values (236, 1, 'Engineering');
insert into subject_area (id, budget_id, title) values (237, 30, 'Sport');
insert into subject_area (id, budget_id, title) values (238, 66, 'Information Systems');
insert into subject_area (id, budget_id, title) values (239, 215, 'Information Systems');
insert into subject_area (id, budget_id, title) values (240, 219, 'Economics');
insert into subject_area (id, budget_id, title) values (241, 190, 'Mechanical');
insert into subject_area (id, budget_id, title) values (242, 69, 'Business');
insert into subject_area (id, budget_id, title) values (243, 96, 'Game Development');
insert into subject_area (id, budget_id, title) values (244, 22, 'Sport');
insert into subject_area (id, budget_id, title) values (245, 138, 'Medicine');
insert into subject_area (id, budget_id, title) values (246, 127, 'Game Development');
insert into subject_area (id, budget_id, title) values (247, 84, 'Law');
insert into subject_area (id, budget_id, title) values (248, 66, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (249, 102, 'Business');
insert into subject_area (id, budget_id, title) values (250, 96, 'Information Systems');
insert into subject_area (id, budget_id, title) values (251, 220, 'Computer Science');
insert into subject_area (id, budget_id, title) values (252, 179, 'Computer Science');
insert into subject_area (id, budget_id, title) values (253, 202, 'Sport');
insert into subject_area (id, budget_id, title) values (254, 110, 'Economics');
insert into subject_area (id, budget_id, title) values (255, 132, 'Engineering');
insert into subject_area (id, budget_id, title) values (256, 69, 'Business');
insert into subject_area (id, budget_id, title) values (257, 127, 'Law');
insert into subject_area (id, budget_id, title) values (258, 72, 'Law');
insert into subject_area (id, budget_id, title) values (259, 80, 'Sport');
insert into subject_area (id, budget_id, title) values (260, 137, 'Business');
insert into subject_area (id, budget_id, title) values (261, 102, 'Business');
insert into subject_area (id, budget_id, title) values (262, 125, 'Medicine');
insert into subject_area (id, budget_id, title) values (263, 21, 'Game Development');
insert into subject_area (id, budget_id, title) values (264, 39, 'Architecture');
insert into subject_area (id, budget_id, title) values (265, 125, 'Mechanical');
insert into subject_area (id, budget_id, title) values (266, 120, 'Computer Science');
insert into subject_area (id, budget_id, title) values (267, 121, 'Game Development');
insert into subject_area (id, budget_id, title) values (268, 97, 'Business');
insert into subject_area (id, budget_id, title) values (269, 228, 'Medicine');
insert into subject_area (id, budget_id, title) values (270, 248, 'Law');
insert into subject_area (id, budget_id, title) values (271, 199, 'Information Systems');
insert into subject_area (id, budget_id, title) values (272, 172, 'Architecture');
insert into subject_area (id, budget_id, title) values (273, 214, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (274, 248, 'Game Development');
insert into subject_area (id, budget_id, title) values (275, 235, 'Architecture');
insert into subject_area (id, budget_id, title) values (276, 13, 'Engineering');
insert into subject_area (id, budget_id, title) values (277, 191, 'Economics');
insert into subject_area (id, budget_id, title) values (278, 148, 'Information Systems');
insert into subject_area (id, budget_id, title) values (279, 241, 'Architecture');
insert into subject_area (id, budget_id, title) values (280, 79, 'Mechanical');
insert into subject_area (id, budget_id, title) values (281, 118, 'Game Development');
insert into subject_area (id, budget_id, title) values (282, 117, 'Law');
insert into subject_area (id, budget_id, title) values (283, 214, 'Sport');
insert into subject_area (id, budget_id, title) values (284, 94, 'Business');
insert into subject_area (id, budget_id, title) values (285, 216, 'Information Systems');
insert into subject_area (id, budget_id, title) values (286, 114, 'Engineering');
insert into subject_area (id, budget_id, title) values (287, 125, 'Computer Science');
insert into subject_area (id, budget_id, title) values (288, 152, 'Architecture');
insert into subject_area (id, budget_id, title) values (289, 184, 'Information Systems');
insert into subject_area (id, budget_id, title) values (290, 85, 'Mechanical');
insert into subject_area (id, budget_id, title) values (291, 215, 'Business');
insert into subject_area (id, budget_id, title) values (292, 72, 'Information Systems');
insert into subject_area (id, budget_id, title) values (293, 245, 'Game Development');
insert into subject_area (id, budget_id, title) values (294, 54, 'Medicine');
insert into subject_area (id, budget_id, title) values (295, 23, 'Architecture');
insert into subject_area (id, budget_id, title) values (296, 20, 'Medicine');
insert into subject_area (id, budget_id, title) values (297, 126, 'Business');
insert into subject_area (id, budget_id, title) values (298, 171, 'Sport');
insert into subject_area (id, budget_id, title) values (299, 216, 'Business');
insert into subject_area (id, budget_id, title) values (300, 69, 'Economics');
insert into subject_area (id, budget_id, title) values (301, 86, 'Economics');
insert into subject_area (id, budget_id, title) values (302, 218, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (303, 188, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (304, 28, 'Engineering');
insert into subject_area (id, budget_id, title) values (305, 141, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (306, 90, 'Architecture');
insert into subject_area (id, budget_id, title) values (307, 52, 'Economics');
insert into subject_area (id, budget_id, title) values (308, 154, 'Mechanical');
insert into subject_area (id, budget_id, title) values (309, 234, 'Sport');
insert into subject_area (id, budget_id, title) values (310, 99, 'Business');
insert into subject_area (id, budget_id, title) values (311, 107, 'Business');
insert into subject_area (id, budget_id, title) values (312, 34, 'Architecture');
insert into subject_area (id, budget_id, title) values (313, 170, 'Medicine');
insert into subject_area (id, budget_id, title) values (314, 244, 'Economics');
insert into subject_area (id, budget_id, title) values (315, 155, 'Computer Science');
insert into subject_area (id, budget_id, title) values (316, 59, 'Economics');
insert into subject_area (id, budget_id, title) values (317, 144, 'Mechanical');
insert into subject_area (id, budget_id, title) values (318, 208, 'Law');
insert into subject_area (id, budget_id, title) values (319, 34, 'Game Development');
insert into subject_area (id, budget_id, title) values (320, 127, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (321, 33, 'Computer Science');
insert into subject_area (id, budget_id, title) values (322, 17, 'Mechanical');
insert into subject_area (id, budget_id, title) values (323, 19, 'Law');
insert into subject_area (id, budget_id, title) values (324, 48, 'Computer Science');
insert into subject_area (id, budget_id, title) values (325, 145, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (326, 125, 'Business');
insert into subject_area (id, budget_id, title) values (327, 107, 'Medicine');
insert into subject_area (id, budget_id, title) values (328, 246, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (329, 49, 'Information Systems');
insert into subject_area (id, budget_id, title) values (330, 50, 'Computer Science');
insert into subject_area (id, budget_id, title) values (331, 58, 'Architecture');
insert into subject_area (id, budget_id, title) values (332, 4, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (333, 226, 'Sport');
insert into subject_area (id, budget_id, title) values (334, 245, 'Sport');
insert into subject_area (id, budget_id, title) values (335, 245, 'Game Development');
insert into subject_area (id, budget_id, title) values (336, 209, 'Architecture');
insert into subject_area (id, budget_id, title) values (337, 206, 'Game Development');
insert into subject_area (id, budget_id, title) values (338, 182, 'Economics');
insert into subject_area (id, budget_id, title) values (339, 203, 'Economics');
insert into subject_area (id, budget_id, title) values (340, 142, 'Business');
insert into subject_area (id, budget_id, title) values (341, 18, 'Engineering');
insert into subject_area (id, budget_id, title) values (342, 210, 'Economics');
insert into subject_area (id, budget_id, title) values (343, 4, 'Medicine');
insert into subject_area (id, budget_id, title) values (344, 184, 'Medicine');
insert into subject_area (id, budget_id, title) values (345, 58, 'Mechanical');
insert into subject_area (id, budget_id, title) values (346, 232, 'Business');
insert into subject_area (id, budget_id, title) values (347, 38, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (348, 77, 'Information Systems');
insert into subject_area (id, budget_id, title) values (349, 98, 'Game Development');
insert into subject_area (id, budget_id, title) values (350, 52, 'Engineering');
insert into subject_area (id, budget_id, title) values (351, 54, 'Economics');
insert into subject_area (id, budget_id, title) values (352, 221, 'Medicine');
insert into subject_area (id, budget_id, title) values (353, 49, 'Law');
insert into subject_area (id, budget_id, title) values (354, 14, 'Business');
insert into subject_area (id, budget_id, title) values (355, 201, 'Business');
insert into subject_area (id, budget_id, title) values (356, 208, 'Business');
insert into subject_area (id, budget_id, title) values (357, 121, 'Engineering');
insert into subject_area (id, budget_id, title) values (358, 147, 'Business');
insert into subject_area (id, budget_id, title) values (359, 191, 'Information Systems');
insert into subject_area (id, budget_id, title) values (360, 91, 'Medicine');
insert into subject_area (id, budget_id, title) values (361, 39, 'Economics');
insert into subject_area (id, budget_id, title) values (362, 55, 'Business');
insert into subject_area (id, budget_id, title) values (363, 93, 'Engineering');
insert into subject_area (id, budget_id, title) values (364, 95, 'Information Systems');
insert into subject_area (id, budget_id, title) values (365, 133, 'Engineering');
insert into subject_area (id, budget_id, title) values (366, 94, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (367, 238, 'Mechanical');
insert into subject_area (id, budget_id, title) values (368, 202, 'Business');
insert into subject_area (id, budget_id, title) values (369, 138, 'Information Systems');
insert into subject_area (id, budget_id, title) values (370, 134, 'Architecture');
insert into subject_area (id, budget_id, title) values (371, 56, 'Medicine');
insert into subject_area (id, budget_id, title) values (372, 118, 'Architecture');
insert into subject_area (id, budget_id, title) values (373, 194, 'Architecture');
insert into subject_area (id, budget_id, title) values (374, 113, 'Engineering');
insert into subject_area (id, budget_id, title) values (375, 222, 'Architecture');
insert into subject_area (id, budget_id, title) values (376, 230, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (377, 92, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (378, 87, 'Sport');
insert into subject_area (id, budget_id, title) values (379, 2, 'Computer Science');
insert into subject_area (id, budget_id, title) values (380, 196, 'Computer Science');
insert into subject_area (id, budget_id, title) values (381, 139, 'Game Development');
insert into subject_area (id, budget_id, title) values (382, 94, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (383, 112, 'Mechanical');
insert into subject_area (id, budget_id, title) values (384, 11, 'Mechanical');
insert into subject_area (id, budget_id, title) values (385, 57, 'Game Development');
insert into subject_area (id, budget_id, title) values (386, 111, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (387, 64, 'Medicine');
insert into subject_area (id, budget_id, title) values (388, 79, 'Computer Science');
insert into subject_area (id, budget_id, title) values (389, 148, 'Medicine');
insert into subject_area (id, budget_id, title) values (390, 127, 'Medicine');
insert into subject_area (id, budget_id, title) values (391, 204, 'Architecture');
insert into subject_area (id, budget_id, title) values (392, 66, 'Mechanical');
insert into subject_area (id, budget_id, title) values (393, 230, 'Engineering');
insert into subject_area (id, budget_id, title) values (394, 68, 'Economics');
insert into subject_area (id, budget_id, title) values (395, 40, 'Medicine');
insert into subject_area (id, budget_id, title) values (396, 144, 'Engineering');
insert into subject_area (id, budget_id, title) values (397, 133, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (398, 249, 'Architecture');
insert into subject_area (id, budget_id, title) values (399, 175, 'Economics');
insert into subject_area (id, budget_id, title) values (400, 9, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (401, 123, 'Business');
insert into subject_area (id, budget_id, title) values (402, 172, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (403, 84, 'Engineering');
insert into subject_area (id, budget_id, title) values (404, 183, 'Information Systems');
insert into subject_area (id, budget_id, title) values (405, 181, 'Business');
insert into subject_area (id, budget_id, title) values (406, 234, 'Engineering');
insert into subject_area (id, budget_id, title) values (407, 174, 'Business');
insert into subject_area (id, budget_id, title) values (408, 168, 'Computer Science');
insert into subject_area (id, budget_id, title) values (409, 32, 'Architecture');
insert into subject_area (id, budget_id, title) values (410, 156, 'Economics');
insert into subject_area (id, budget_id, title) values (411, 32, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (412, 95, 'Computer Science');
insert into subject_area (id, budget_id, title) values (413, 137, 'Economics');
insert into subject_area (id, budget_id, title) values (414, 211, 'Mechanical');
insert into subject_area (id, budget_id, title) values (415, 105, 'Sport');
insert into subject_area (id, budget_id, title) values (416, 95, 'Computer Science');
insert into subject_area (id, budget_id, title) values (417, 58, 'Computer Science');
insert into subject_area (id, budget_id, title) values (418, 68, 'Economics');
insert into subject_area (id, budget_id, title) values (419, 142, 'Information Systems');
insert into subject_area (id, budget_id, title) values (420, 159, 'Economics');
insert into subject_area (id, budget_id, title) values (421, 7, 'Information Systems');
insert into subject_area (id, budget_id, title) values (422, 81, 'Law');
insert into subject_area (id, budget_id, title) values (423, 175, 'Law');
insert into subject_area (id, budget_id, title) values (424, 202, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (425, 146, 'Computer Science');
insert into subject_area (id, budget_id, title) values (426, 44, 'Law');
insert into subject_area (id, budget_id, title) values (427, 63, 'Business');
insert into subject_area (id, budget_id, title) values (428, 177, 'Engineering');
insert into subject_area (id, budget_id, title) values (429, 81, 'Business');
insert into subject_area (id, budget_id, title) values (430, 95, 'Mechanical');
insert into subject_area (id, budget_id, title) values (431, 61, 'Game Development');
insert into subject_area (id, budget_id, title) values (432, 92, 'Architecture');
insert into subject_area (id, budget_id, title) values (433, 102, 'Economics');
insert into subject_area (id, budget_id, title) values (434, 220, 'Computer Science');
insert into subject_area (id, budget_id, title) values (435, 108, 'Law');
insert into subject_area (id, budget_id, title) values (436, 121, 'Sport');
insert into subject_area (id, budget_id, title) values (437, 185, 'Game Development');
insert into subject_area (id, budget_id, title) values (438, 1, 'Mechanical');
insert into subject_area (id, budget_id, title) values (439, 33, 'Computer Science');
insert into subject_area (id, budget_id, title) values (440, 100, 'Engineering');
insert into subject_area (id, budget_id, title) values (441, 238, 'Business');
insert into subject_area (id, budget_id, title) values (442, 104, 'Computer Science');
insert into subject_area (id, budget_id, title) values (443, 84, 'Mechanical');
insert into subject_area (id, budget_id, title) values (444, 116, 'Mechanical');
insert into subject_area (id, budget_id, title) values (445, 44, 'Game Development');
insert into subject_area (id, budget_id, title) values (446, 72, 'Medicine');
insert into subject_area (id, budget_id, title) values (447, 110, 'Mechanical');
insert into subject_area (id, budget_id, title) values (448, 187, 'Engineering');
insert into subject_area (id, budget_id, title) values (449, 1, 'Information Systems');
insert into subject_area (id, budget_id, title) values (450, 206, 'Law');
insert into subject_area (id, budget_id, title) values (451, 202, 'Law');
insert into subject_area (id, budget_id, title) values (452, 68, 'Economics');
insert into subject_area (id, budget_id, title) values (453, 17, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (454, 146, 'Engineering');
insert into subject_area (id, budget_id, title) values (455, 58, 'Engineering');
insert into subject_area (id, budget_id, title) values (456, 60, 'Sport');
insert into subject_area (id, budget_id, title) values (457, 3, 'Economics');
insert into subject_area (id, budget_id, title) values (458, 72, 'Game Development');
insert into subject_area (id, budget_id, title) values (459, 45, 'Architecture');
insert into subject_area (id, budget_id, title) values (460, 107, 'Architecture');
insert into subject_area (id, budget_id, title) values (461, 77, 'Computer Science');
insert into subject_area (id, budget_id, title) values (462, 65, 'Mechanical');
insert into subject_area (id, budget_id, title) values (463, 64, 'Architecture');
insert into subject_area (id, budget_id, title) values (464, 126, 'Engineering');
insert into subject_area (id, budget_id, title) values (465, 180, 'Game Development');
insert into subject_area (id, budget_id, title) values (466, 141, 'Game Development');
insert into subject_area (id, budget_id, title) values (467, 191, 'Economics');
insert into subject_area (id, budget_id, title) values (468, 115, 'Law');
insert into subject_area (id, budget_id, title) values (469, 204, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (470, 187, 'Business');
insert into subject_area (id, budget_id, title) values (471, 163, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (472, 10, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (473, 201, 'Engineering');
insert into subject_area (id, budget_id, title) values (474, 75, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (475, 213, 'Law');
insert into subject_area (id, budget_id, title) values (476, 81, 'Computer Science');
insert into subject_area (id, budget_id, title) values (477, 14, 'Engineering');
insert into subject_area (id, budget_id, title) values (478, 220, 'Economics');
insert into subject_area (id, budget_id, title) values (479, 9, 'Architecture');
insert into subject_area (id, budget_id, title) values (480, 201, 'Law');
insert into subject_area (id, budget_id, title) values (481, 20, 'Engineering');
insert into subject_area (id, budget_id, title) values (482, 57, 'Engineering');
insert into subject_area (id, budget_id, title) values (483, 189, 'Mechanical');
insert into subject_area (id, budget_id, title) values (484, 118, 'Information Systems');
insert into subject_area (id, budget_id, title) values (485, 117, 'Architecture');
insert into subject_area (id, budget_id, title) values (486, 94, 'Engineering');
insert into subject_area (id, budget_id, title) values (487, 225, 'Mechanical');
insert into subject_area (id, budget_id, title) values (488, 237, 'Economics');
insert into subject_area (id, budget_id, title) values (489, 9, 'Computer Science');
insert into subject_area (id, budget_id, title) values (490, 82, 'Business');
insert into subject_area (id, budget_id, title) values (491, 212, 'Economics');
insert into subject_area (id, budget_id, title) values (492, 86, 'Medicine');
insert into subject_area (id, budget_id, title) values (493, 53, 'Information Systems');
insert into subject_area (id, budget_id, title) values (494, 214, 'Medicine');
insert into subject_area (id, budget_id, title) values (495, 220, 'Economics');
insert into subject_area (id, budget_id, title) values (496, 179, 'Game Development');
insert into subject_area (id, budget_id, title) values (497, 52, 'Mechanical');
insert into subject_area (id, budget_id, title) values (498, 191, 'Information Systems');
insert into subject_area (id, budget_id, title) values (499, 169, 'Information Systems');
insert into subject_area (id, budget_id, title) values (500, 51, 'Computer Science');
