insert into subject_area (id, budget_id, title) values (1, 52, 'Computer Science');
insert into subject_area (id, budget_id, title) values (2, 62, 'Mechanical');
insert into subject_area (id, budget_id, title) values (3, 85, 'Mechanical');
insert into subject_area (id, budget_id, title) values (4, 43, 'Management Studies');
insert into subject_area (id, budget_id, title) values (5, 57, 'Engineering');
insert into subject_area (id, budget_id, title) values (6, 70, 'Mechanical');
insert into subject_area (id, budget_id, title) values (7, 73, 'Manufacturing Engineering');
insert into subject_area (id, budget_id, title) values (8, 4, 'Gave Dev');
insert into subject_area (id, budget_id, title) values (9, 25, 'Architecture');
insert into subject_area (id, budget_id, title) values (10, 29, 'Mechanical');
insert into subject_area (id, budget_id, title) values (11, 12, 'Econometrics');
insert into subject_area (id, budget_id, title) values (12, 50, 'Architecture');
insert into subject_area (id, budget_id, title) values (13, 29, 'Manufacturing Engineering');
insert into subject_area (id, budget_id, title) values (14, 94, 'Architecture');
insert into subject_area (id, budget_id, title) values (15, 95, 'Management Studies');
insert into subject_area (id, budget_id, title) values (16, 41, 'Architecture');
insert into subject_area (id, budget_id, title) values (17, 3, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (18, 93, 'Manufacturing Engineering');
insert into subject_area (id, budget_id, title) values (19, 89, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (20, 95, 'Business');
insert into subject_area (id, budget_id, title) values (21, 10, 'Gave Dev');
insert into subject_area (id, budget_id, title) values (22, 42, 'Law');
insert into subject_area (id, budget_id, title) values (23, 11, 'Mechanical');
insert into subject_area (id, budget_id, title) values (24, 88, 'Business');
insert into subject_area (id, budget_id, title) values (25, 59, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (26, 93, 'Computer Science');
insert into subject_area (id, budget_id, title) values (27, 11, 'Management Studies');
insert into subject_area (id, budget_id, title) values (28, 3, 'Management Studies');
insert into subject_area (id, budget_id, title) values (29, 95, 'Management Studies');
insert into subject_area (id, budget_id, title) values (30, 86, 'Mechanical');
insert into subject_area (id, budget_id, title) values (31, 75, 'Law');
insert into subject_area (id, budget_id, title) values (32, 41, 'Architecture');
insert into subject_area (id, budget_id, title) values (33, 36, 'Computer Science');
insert into subject_area (id, budget_id, title) values (34, 95, 'Econometrics');
insert into subject_area (id, budget_id, title) values (35, 34, 'Business');
insert into subject_area (id, budget_id, title) values (36, 16, 'Engineering');
insert into subject_area (id, budget_id, title) values (37, 82, 'Manufacturing Engineering');
insert into subject_area (id, budget_id, title) values (38, 30, 'Architecture');
insert into subject_area (id, budget_id, title) values (39, 56, 'Engineering');
insert into subject_area (id, budget_id, title) values (40, 29, 'Management Studies');
insert into subject_area (id, budget_id, title) values (41, 61, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (42, 61, 'Management Studies');
insert into subject_area (id, budget_id, title) values (43, 29, 'Law');
insert into subject_area (id, budget_id, title) values (44, 16, 'Computer Science');
insert into subject_area (id, budget_id, title) values (45, 50, 'Computer Science');
insert into subject_area (id, budget_id, title) values (46, 26, 'Econometrics');
insert into subject_area (id, budget_id, title) values (47, 43, 'Architecture');
insert into subject_area (id, budget_id, title) values (48, 15, 'Mechanical');
insert into subject_area (id, budget_id, title) values (49, 81, 'Manufacturing Engineering');
insert into subject_area (id, budget_id, title) values (50, 30, 'Econometrics');
insert into subject_area (id, budget_id, title) values (51, 20, 'Mechanical');
insert into subject_area (id, budget_id, title) values (52, 9, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (53, 70, 'Business');
insert into subject_area (id, budget_id, title) values (54, 62, 'Business');
insert into subject_area (id, budget_id, title) values (55, 13, 'Management Studies');
insert into subject_area (id, budget_id, title) values (56, 2, 'Computer Science');
insert into subject_area (id, budget_id, title) values (57, 15, 'Business');
insert into subject_area (id, budget_id, title) values (58, 88, 'Gave Dev');
insert into subject_area (id, budget_id, title) values (59, 21, 'Mechanical');
insert into subject_area (id, budget_id, title) values (60, 33, 'Econometrics');
insert into subject_area (id, budget_id, title) values (61, 56, 'Manufacturing Engineering');
insert into subject_area (id, budget_id, title) values (62, 47, 'Gave Dev');
insert into subject_area (id, budget_id, title) values (63, 95, 'Mechanical');
insert into subject_area (id, budget_id, title) values (64, 91, 'Management Studies');
insert into subject_area (id, budget_id, title) values (65, 86, 'Architecture');
insert into subject_area (id, budget_id, title) values (66, 56, 'Manufacturing Engineering');
insert into subject_area (id, budget_id, title) values (67, 88, 'Business');
insert into subject_area (id, budget_id, title) values (68, 30, 'Business');
insert into subject_area (id, budget_id, title) values (69, 100, 'Engineering');
insert into subject_area (id, budget_id, title) values (70, 46, 'Architecture');
insert into subject_area (id, budget_id, title) values (71, 80, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (72, 84, 'Management Studies');
insert into subject_area (id, budget_id, title) values (73, 19, 'Engineering');
insert into subject_area (id, budget_id, title) values (74, 27, 'Management Studies');
insert into subject_area (id, budget_id, title) values (75, 83, 'Architecture');
insert into subject_area (id, budget_id, title) values (76, 91, 'Manufacturing Engineering');
insert into subject_area (id, budget_id, title) values (77, 84, 'Computer Science');
insert into subject_area (id, budget_id, title) values (78, 37, 'Gave Dev');
insert into subject_area (id, budget_id, title) values (79, 73, 'Management Studies');
insert into subject_area (id, budget_id, title) values (80, 71, 'Management Studies');
insert into subject_area (id, budget_id, title) values (81, 28, 'Gave Dev');
insert into subject_area (id, budget_id, title) values (82, 6, 'Computer Science');
insert into subject_area (id, budget_id, title) values (83, 80, 'Gave Dev');
insert into subject_area (id, budget_id, title) values (84, 76, 'Architecture');
insert into subject_area (id, budget_id, title) values (85, 78, 'Business');
insert into subject_area (id, budget_id, title) values (86, 33, 'Computer Science');
insert into subject_area (id, budget_id, title) values (87, 96, 'Mechanical');
insert into subject_area (id, budget_id, title) values (88, 33, 'Aeronautical');
insert into subject_area (id, budget_id, title) values (89, 70, 'Gave Dev');
insert into subject_area (id, budget_id, title) values (90, 68, 'Business');
insert into subject_area (id, budget_id, title) values (91, 75, 'Mechanical');
insert into subject_area (id, budget_id, title) values (92, 37, 'Business');
insert into subject_area (id, budget_id, title) values (93, 77, 'Computer Science');
insert into subject_area (id, budget_id, title) values (94, 72, 'Mechanical');
insert into subject_area (id, budget_id, title) values (95, 52, 'Business');
insert into subject_area (id, budget_id, title) values (96, 61, 'Gave Dev');
insert into subject_area (id, budget_id, title) values (97, 42, 'Business');
insert into subject_area (id, budget_id, title) values (98, 36, 'Business');
insert into subject_area (id, budget_id, title) values (99, 9, 'Engineering');
insert into subject_area (id, budget_id, title) values (100, 94, 'Business');
